spring.application.name=SkyBookAI

spring.datasource.url=jdbc:mysql://localhost:3306/skybookdb
spring.datasource.username=root
spring.datasource.password=sreyah@skybookai

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true